<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>biogram package • biogram</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha256-916EbMg70RQy9LHiGkXzG8hSg9EdNy97GazNG/aiY1w=" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/all.min.css" integrity="sha256-nAmazAk6vS34Xqo0BSrTb+abbtFlgsFK7NKSi6o7Y78=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.7.1/css/v4-shims.min.css" integrity="sha256-6qHlizsOWFskGlwVOKuns+D1nB6ssZrHQrNj1wGplHc=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/headroom.min.js" integrity="sha256-DJFC1kqIhelURkuza0AvYal5RxMtpzLjFhsnVIeuk+U=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.9.4/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="biogram package">
<meta property="og:description" content="">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">biogram</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.6.3</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fas fa fas fa-home fa-lg"></span>
     
  </a>
</li>
<li>
  <a href="../reference/index.html">Reference</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Articles
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/overview.html">biogram package</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/michbur/biogram">
    <span class="fab fa fab fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>biogram package</h1>
                        <h4 class="author">Michał Burdukiewicz, Piotr Sobczyk</h4>
            
            <h4 class="date">5.01.2017</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/michbur/biogram/blob/master/vignettes/overview.Rmd"><code>vignettes/overview.Rmd</code></a></small>
      <div class="hidden name"><code>overview.Rmd</code></div>

    </div>

    
    
<div id="reduction-of-dimensionality" class="section level1">
<h1 class="hasAnchor">
<a href="#reduction-of-dimensionality" class="anchor"></a>Reduction of dimensionality</h1>
<p>Since the number of potential n-grams grows exponentially with the <span class="math inline">\(n\)</span>, n-gram datasets are often very large. To deal with the curse of dimensionality, the <strong>biogram</strong> package offers two solutions. The first relies on the reduction of an alphabet, which is a common approach in case of analysis of amino acid sequences (<span class="citation">Murphy, Wallqvist, and Levy (2000)</span>) and less applied in studies of nucleic acids.</p>
<p>The alternate solution is to filter the non-informative n-grams. The <strong>biogram</strong> package employs feature selection algorithm QuiPT, which allows very fast feature filtering.</p>
<div id="alphabet-reduction" class="section level2">
<h2 class="hasAnchor">
<a href="#alphabet-reduction" class="anchor"></a>Alphabet reduction</h2>
<p>In many cases the properties of the sequences are not depending on the exact sequence of the amino acids, but rather on their physicochemical properties. In this case, the full amino acid alphabet may be replaced with a shorter alphabet, where amino acids are aggregated to larger groups using some design criteria as physicochemical properties. The <strong>biogram</strong> package supports creation of reduced amino acid alphabets and their analysis by two distance measures: similarity index and encoding distance.</p>
<div id="similarity-index" class="section level3">
<h3 class="hasAnchor">
<a href="#similarity-index" class="anchor"></a>Similarity index</h3>
<p>The similarity index, as computed by the <em>calc_si</em> function, was firstly introduced as the unnamed distance measure for reduced alphabets by <span class="citation">Stephenson and Freeland (2013)</span>. Briefly, if a pair of elements is in both encodings in the same group or in different groups, the pair scores 1 and in the opposite case 0. The pairs of the identical elements are ignored. The score is later divided by the number of possible pairs (<span class="math inline">\(20 \times 19\)</span> in case of the amino acid alphabet).</p>
<p><span class="math inline">\(A\)</span>: an alphabet.</p>
<p><span class="math inline">\(a_1\)</span>: an element in the reduced alphabet 1.</p>
<p><span class="math inline">\(a_2\)</span>: an element in the reduced alphabet 2.</p>
<p><span class="math display">\[
S = \sum_{a_1 \in A} \sum_{a_2 \in A, a_2 \neq a_1 } \sum_{enc_1 \in encodings_1} \sum_{enc_2 \in encodings_2} 1_{a_1 \in enc_1 \land a_2 \in enc_2}
\]</span></p>
<p><span class="math display">\[
I_S = \frac{S}{ |A|^2 - |A| }
\]</span></p>
</div>
<div id="encoding-distance" class="section level3">
<h3 class="hasAnchor">
<a href="#encoding-distance" class="anchor"></a>Encoding distance</h3>
<p>The encoding distance, as computed per the <em>calc_ed</em> function, is defined as the minimum number of amino acids that have to be moved between subgroups of encoding to make <strong>a</strong> identical to <strong>b</strong> (the order of subgroups in the encoding and amino acids in a group is unimportant).</p>
<p>This measure may be further normalized by a factor reflecting how much moving amino acids between groups altered mean group properties. Such behavior if generated by specifying parameter <em>prop</em>.</p>
<table class="table">
<caption>Encoding A</caption>
<thead><tr class="header">
<th align="right">ID</th>
<th align="left">Groups</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">P</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">F, I, W, Y</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">A, C, D, E, G, H, K, L, M, N, Q, R, S, T, V</td>
</tr>
</tbody>
</table>
<table class="table">
<caption>Encoding B</caption>
<thead><tr class="header">
<th align="right">ID</th>
<th align="left">Groups</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="left">F, R, W, Y</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="left">C, I, L, T, V</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="left">A, D, E, G, H, K, M, N, P, Q, S</td>
</tr>
</tbody>
</table>
<p>The encoding distance between both groups is 7.</p>
<p><img src="overview_files/figure-html/unnamed-chunk-4-1.png" width="672"></p>
<p>The figure above represents the distances between groups of encoding <strong>a</strong> (green dots) and groups of encoding <strong>b</strong> (red dots). The position of the dot defined by mean values of specific properties of all amino acids belonging to the group.</p>
<table class="table">
<caption>Distances between groups of encodings a and b.</caption>
<thead><tr class="header">
<th></th>
<th align="right">Enc a, group 1</th>
<th align="right">Enc a, group 2</th>
<th align="right">Enc a, group 3</th>
</tr></thead>
<tbody>
<tr class="odd">
<td>Enc b, group 1</td>
<td align="right">0.7681436</td>
<td align="right">0.1786769</td>
<td align="right">0.5441119</td>
</tr>
<tr class="even">
<td>Enc b, group 2</td>
<td align="right">0.6910472</td>
<td align="right">0.3677947</td>
<td align="right">0.4150182</td>
</tr>
<tr class="odd">
<td>Enc b, group 3</td>
<td align="right">0.1219397</td>
<td align="right">0.7645517</td>
<td align="right">0.1558620</td>
</tr>
</tbody>
</table>
<p>The scale factor <span class="math inline">\(s\)</span> for the encoding distance between the encoding <strong>a</strong> with <span class="math inline">\(n\)</span> subgroups (enumerated with <span class="math inline">\(i\)</span>) and the encoding <strong>b</strong> with <span class="math inline">\(m\)</span> subgroups (enumerated with <span class="math inline">\(j\)</span>), we first calculated <span class="math inline">\(p_i\)</span> and <span class="math inline">\(q_j\)</span>, i.e. the mean values of corresponding physicochemical properties of all amino acids for each subgroup.</p>
<p><span class="math display">\[ 
s_{ab} = \sum^n_{i = 1}  \left( \min_{j=1,\dots,m} \; \; \sum^L_{l=1} \sqrt{ 
(p_{i,l} - q_{j,l})^2} \right) 
\]</span></p>
<p>In the case depicted above, <span class="math inline">\(s_{ab}\)</span> is equal to the sum of 0.1219, 0.1787, 0.1559: 0.4565.</p>
<div id="biogram-implementation" class="section level4">
<h4 class="hasAnchor">
<a href="#biogram-implementation" class="anchor"></a>biogram implementation</h4>
<p>The encoding distance is computed with the <em>calc_ed</em> function.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" data-line-number="1"><span class="co"># define two encodings</span></a>
<a class="sourceLine" id="cb1-2" data-line-number="2">a &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="st">`</span><span class="dt">1</span><span class="st">`</span> =<span class="st"> "p"</span>, </a>
<a class="sourceLine" id="cb1-3" data-line-number="3">          <span class="st">`</span><span class="dt">2</span><span class="st">`</span> =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"f"</span>, <span class="st">"i"</span>, <span class="st">"w"</span>, <span class="st">"y"</span>), </a>
<a class="sourceLine" id="cb1-4" data-line-number="4">          <span class="st">`</span><span class="dt">3</span><span class="st">`</span> =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"a"</span>, <span class="st">"c"</span>, <span class="st">"d"</span>, <span class="st">"e"</span>, <span class="st">"g"</span>, <span class="st">"h"</span>, <span class="st">"k"</span>, <span class="st">"l"</span>, <span class="st">"m"</span>, <span class="st">"n"</span>, <span class="st">"q"</span>, <span class="st">"r"</span>, <span class="st">"s"</span>, <span class="st">"t"</span>, <span class="st">"v"</span>))</a>
<a class="sourceLine" id="cb1-5" data-line-number="5"></a>
<a class="sourceLine" id="cb1-6" data-line-number="6">b &lt;-<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/list.html">list</a></span>(<span class="st">`</span><span class="dt">1</span><span class="st">`</span> =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"f"</span>, <span class="st">"r"</span>, <span class="st">"w"</span>, <span class="st">"y"</span>), </a>
<a class="sourceLine" id="cb1-7" data-line-number="7">          <span class="st">`</span><span class="dt">2</span><span class="st">`</span> =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"c"</span>, <span class="st">"i"</span>, <span class="st">"l"</span>, <span class="st">"t"</span>, <span class="st">"v"</span>), </a>
<a class="sourceLine" id="cb1-8" data-line-number="8">          <span class="st">`</span><span class="dt">3</span><span class="st">`</span> =<span class="st"> </span><span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="st">"a"</span>, <span class="st">"d"</span>, <span class="st">"e"</span>, <span class="st">"g"</span>, <span class="st">"h"</span>, <span class="st">"k"</span>, <span class="st">"m"</span>, <span class="st">"n"</span>, <span class="st">"p"</span>, <span class="st">"q"</span>, <span class="st">"s"</span>))</a>
<a class="sourceLine" id="cb1-9" data-line-number="9"></a>
<a class="sourceLine" id="cb1-10" data-line-number="10"><span class="co"># calculate encoding distance</span></a>
<a class="sourceLine" id="cb1-11" data-line-number="11"><span class="kw"><a href="../reference/calc_ed.html">calc_ed</a></span>(<span class="dt">a =</span> a, <span class="dt">b =</span> b, <span class="dt">measure =</span> <span class="st">"pi"</span>)</a></code></pre></div>
<pre><code>## [1] 7</code></pre>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" data-line-number="1"><span class="co"># get properties from aaprop dataset and calculate normalized encoding distance</span></a>
<a class="sourceLine" id="cb3-2" data-line-number="2"><span class="kw"><a href="https://rdrr.io/r/utils/data.html">data</a></span>(aaprop)</a>
<a class="sourceLine" id="cb3-3" data-line-number="3"><span class="kw"><a href="../reference/calc_ed.html">calc_ed</a></span>(<span class="dt">a =</span> a, <span class="dt">b =</span> b, <span class="dt">measure =</span> <span class="st">"pi"</span>, <span class="dt">prop =</span> aaprop[<span class="kw"><a href="https://rdrr.io/r/base/c.html">c</a></span>(<span class="dv">22</span>, <span class="dv">211</span>), ])</a></code></pre></div>
<pre><code>## [1] 3.19535</code></pre>
</div>
</div>
<div id="quick-permutation-test-quipt" class="section level3">
<h3 class="hasAnchor">
<a href="#quick-permutation-test-quipt" class="anchor"></a>Quick Permutation Test (QuiPT)</h3>
<p>QuiPT is fast solution for filtering a large number of binary features provided that target vector is also binary. It is typical case for positioned n-gram data. Moreover, even considering unpositioned n-grams, if the <span class="math inline">\(n\)</span> is sufficiently high, the matrix of counts is almost sparse and little to no information is lost after data is artificially binarized.</p>
<p>The simplest use case of QuiPT is a case of two Bernoulli random variables. One of them is feature, the other is target. We are interested in deciding whether feature brings some important information about target. The <strong>biogram</strong> package employs several measures of such a dependence (see <code><a href="../reference/calc_criterion.html">?calc_criterion</a></code>). We shall consider in detail only information gain, but similar conclusions can be done for other measures.</p>
<div id="definition---entropy" class="section level5">
<h5 class="hasAnchor">
<a href="#definition---entropy" class="anchor"></a>Definition - entropy</h5>
<p>For a discrete random variable we define entropy by: <span class="math display">\[ H(X) = - \sum^m p_j log p_j\]</span> For a Bernoulli r.v. we get a simplified expression <span class="math display">\[ H(X) = -p \cdot log(p) - (1-p) \cdot log(1-p)\]</span></p>
</div>
<div id="definition---conditional-entropy" class="section level5">
<h5 class="hasAnchor">
<a href="#definition---conditional-entropy" class="anchor"></a>Definition - conditional entropy</h5>
<p>For two discrete r.v. X, Y we define average conditional entropy by: <span class="math display">\[H(Y|X) = \sum_j P(X=v_j) H(Y|X=v_j)\]</span> If X and Y are Bernoulli’s then: <span class="math display">\[H(Y|X) = q \cdot H(Y|X=1) + (1-q) \cdot H(Y|X=0)\]</span></p>
</div>
<div id="definition---information-gain" class="section level5">
<h5 class="hasAnchor">
<a href="#definition---information-gain" class="anchor"></a>Definition - Information gain</h5>
<p><span class="math display">\[IG(Y|X) = H(Y) - H(Y|X)\]</span></p>
<p>The intuition is that: &gt; IG tells you how interesting a 2-d contingency table is going to be</p>
<p>In our application, analysis of n-grams, we are interested in Bernoulli r.v. Let us consider the contingency table we get:</p>
<table class="table">
<thead><tr class="header">
<th align="center">target\feature</th>
<th align="center">1</th>
<th align="center">0</th>
</tr></thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center"><span class="math inline">\(n_{1,1}\)</span></td>
<td align="center"><span class="math inline">\(n_{1,0}\)</span></td>
</tr>
<tr class="even">
<td align="center">0</td>
<td align="center"><span class="math inline">\(n_{0,1}\)</span></td>
<td align="center"><span class="math inline">\(n_{0,0}\)</span></td>
</tr>
</tbody>
</table>
</div>
<div id="computing-ig-distribution-under-null-hypothesis" class="section level4">
<h4 class="hasAnchor">
<a href="#computing-ig-distribution-under-null-hypothesis" class="anchor"></a>Computing IG distribution under null hypothesis</h4>
<p>As can be seen above we have 4 possible outcomes. If probability that target equals 1 is <span class="math inline">\(p\)</span> and probability that feature equals 1 is <span class="math inline">\(q\)</span> and feature and target are independent then each of them has the following probabilities <span class="math display">\[P((Target, Feature) = (1,1)) = p \cdot q\]</span> <span class="math display">\[P((Target, Feature) = (1,0)) = p \cdot (1-q)\]</span> <span class="math display">\[P((Target, Feature) = (0,1)) = (1-p) \cdot q\]</span> <span class="math display">\[P((Target, Feature) = (0,0)) = (1-p) \cdot (1-q)\]</span></p>
<p>This means that a target-feature can be described as multinomial distribution:</p>
<p><span class="math display">\[ 
\begin{aligned}
{n \choose n_{1,1}} (p\cdot q)^{n_{1,1}} 
{n - n_{1,1} \choose n_{1,0}} (p\cdot (1-q))^{n_{1,0}}
{n - n_{1,1} - n_{1,0} \choose n_{0,1}} ((1-p)\cdot q)^{n_{0,1}} \\
{n - n_{1,1} - n_{1,0} -n_{0,1}\choose n_{0,0}} ((1-p)\cdot (1-q))^{n_{0,0}}
\end{aligned}
\]</span></p>
<p>However we have important restriction that <span class="math inline">\(n_{1,\cdot} = n_{1,1} + n_{1,0}\)</span> and <span class="math inline">\(n_{\cdot, 1} = n_{1,1} + n_{0,1}\)</span> are known and fixed as they describe the number of “ones” for target and feature respectively.</p>
<p>This might look very complicated but this restriction in fact simplifies our computation significantly.</p>
<p>Observe that <span class="math inline">\(n_{1,1}\)</span> is from range <span class="math inline">\([0,min(n_{\cdot, 1}, n_{1, \cdot})]\)</span>. So we get probability of certain contingency table as conditional distribution, as impose restrictions on two parameters <span class="math inline">\(n_{\cdot, 1}\)</span> and <span class="math inline">\(n_{1, \cdot}\)</span> We can compute IG for each possible value of <span class="math inline">\(n_{1,1}\)</span> and finally we get distribution of Information Gain under hypothesis that target and feature are independent.</p>
<p>The calculation of distributions is performed by <code>distr_crit</code> function. To facilitate time-consuming computations when dealing with a very large number of features, we introduce a possibility to set the limit of calculated contingence matrices using <code>iter_limit</code> parameter. By default, IG is calculated for 200 contingence matrices, therefore we get an approximate distribution of Information Gain.</p>
<p>Having exact or even approximate (when limiting the number of calculated contingence matrices) distribution lets us perform permutation test much quicker as we no longer need to perform any replications. Furthermore, by using exact test we will get precise values of tails which was not guaranteed with random permutations.</p>
</div>
</div>
</div>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<div id="refs" class="references">
<div id="ref-murphy_simplified_2000">
<p>Murphy, Lynne Reed, Anders Wallqvist, and Ronald M. Levy. 2000. “Simplified Amino Acid Alphabets for Protein Fold Recognition and Implications for Folding.” <em>Protein Engineering</em> 13 (3): 149–52. <a href="https://doi.org/10.1093/protein/13.3.149">https://doi.org/10.1093/protein/13.3.149</a>.</p>
</div>
<div id="ref-stephenson_unearthing_2013">
<p>Stephenson, James D., and Stephen J. Freeland. 2013. “Unearthing the Root of Amino Acid Similarity.” <em>Journal of Molecular Evolution</em> 77 (4): 159–69. <a href="https://doi.org/10.1007/s00239-013-9565-0">https://doi.org/10.1007/s00239-013-9565-0</a>.</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">

        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li>
<a href="#reduction-of-dimensionality">Reduction of dimensionality</a><ul class="nav nav-pills nav-stacked">
<li><a href="#alphabet-reduction">Alphabet reduction</a></li>
      </ul>
</li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>



      <footer><div class="copyright">
  <p>Developed by Michal Burdukiewicz, Piotr Sobczyk, Chris Lauber, Dominik Rafacz.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.4.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
